name: test_shader
type: graphics
stages:
  - type: vertex
    path: test_shader.vert.glsl
  - type: fragment
    path: test_shader.frag.glsl
options:
  depth_test_enable: false
  depth_write_enable: true
  depth_compare_op: less
  primitive_topology: triangle_list
  cull_mode: back
  polygon_mode: line
  front_face: counter_clockwise
bindings:
  - binding: 0
    input_rate: vertex
    stride: 12
  - binding: 1
    input_rate: instance
    stride: 12
attributes:
  - type: float3 # model position
    location: 0
    binding: 0
    offset: 0
  - type: float3 # instance position
    location: 1
    binding: 1
    offset: 0
