#pragma once

#include "keycodes.h"

namespace Toki {

    enum class ScanCode {
        SCAN_UNKNOWN,

        SCAN_0 = 48,
        SCAN_1 = 49,
        SCAN_2 = 50,
        SCAN_3 = 51,
        SCAN_4 = 52,
        SCAN_5 = 53,
        SCAN_6 = 54,
        SCAN_7 = 55,
        SCAN_8 = 56,
        SCAN_9 = 57,

        SCAN_A = 65,
        SCAN_B,
        SCAN_C,
        SCAN_D,
        SCAN_E,
        SCAN_F,
        SCAN_G,
        SCAN_H,
        SCAN_I,
        SCAN_J,
        SCAN_K,
        SCAN_L,
        SCAN_M,
        SCAN_N,
        SCAN_O,
        SCAN_P,
        SCAN_Q,
        SCAN_R,
        SCAN_S,
        SCAN_T,
        SCAN_U,
        SCAN_V,
        SCAN_W,
        SCAN_X,
        SCAN_Y,
        SCAN_Z,

        SCAN_SPACE = 32,
        SCAN_APOSTROPHE = 39,
        SCAN_COMMA = 44,
        SCAN_MINUS = 45,
        SCAN_EQUAL = 61,
        SCAN_LEFT_BRACKET = 91,
        SCAN_BACKSLASH = 92,
        SCAN_RIGHT_BRACKET = 93,
        SCAN_GRAVE_ACCENT = 96,
        SCAN_EXTRA_1 = 128,
        SCAN_EXTRA_2 = 129,

        SCAN_F1 = 256,
        SCAN_F2,
        SCAN_F3,
        SCAN_F4,
        SCAN_F5,
        SCAN_F6,
        SCAN_F7,
        SCAN_F8,
        SCAN_F9,
        SCAN_F10,
        SCAN_F11,
        SCAN_F12,
        SCAN_F13,
        SCAN_F14,
        SCAN_F15,
        SCAN_F16,
        SCAN_F17,
        SCAN_F18,
        SCAN_F19,
        SCAN_F20,
        SCAN_F21,
        SCAN_F22,
        SCAN_F23,
        SCAN_F24,
        SCAN_F25,

        SCAN_ESCAPE,
        SCAN_ENTER,
        SCAN_TAB,
        SCAN_BACKSPACE,
        SCAN_INSERT,
        SCAN_DELETE,
        SCAN_PAGE_UP,
        SCAN_PAGE_DOWN,
        SCAN_HOME,
        SCAN_END,
        SCAN_CAPS_LOCK,
        SCAN_SCROLL_LOCK,
        SCAN_NUM_LOCK,
        SCAN_PRINT_SCREEN,
        SCAN_PAUSE,

        SCAN_RIGHT,
        SCAN_LEFT,
        SCAN_UP,
        SCAN_DOWN,

        SCAN_KEYPAD_0,
        SCAN_KEYPAD_1,
        SCAN_KEYPAD_2,
        SCAN_KEYPAD_3,
        SCAN_KEYPAD_4,
        SCAN_KEYPAD_5,
        SCAN_KEYPAD_6,
        SCAN_KEYPAD_7,
        SCAN_KEYPAD_8,
        SCAN_KEYPAD_9,
        SCAN_KEYPAD_SLASH,
        SCAN_KEYPAD_ASTERISK,
        SCAN_KEYPAD_MINUS,
        SCAN_KEYPAD_PLUS,
        SCAN_KEYPAD_ENTER,
        SCAN_KEYPAD_COMMA,

        SCAN_LEFT_SHIFT,
        SCAN_LEFT_CONTROL,
        SCAN_LEFT_ALT,
        SCAN_LEFT_SUPER,
        SCAN_RIGHT_SHIFT,
        SCAN_RIGHT_CONTROL,
        SCAN_RIGHT_ALT,
        SCAN_RIGHT_SUPER,
        SCAN_MENU
    };

    enum class MouseButton {
        Left, Right, Middle,
        Button1, Button2 // ... add more if needed
    };

    ScanCode mapKeyCode(KeyCode code, std::unordered_map<KeyCode, ScanCode> layoutMap);

}